BEW-1.2-Final-Project/students_app/main/routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user
from datetime import date, datetime
from students_app.models import  User, Student, Professor, Class
from students_app.main.forms import StudentForm, ProfessorForm, ClassForm
from students_app import bcrypt

# Import app and db
from students_app import app, db
main = Blueprint('main', __name__)

# Create your routes here.
@main.route('/')
def homepage():
    ''' Delivers homepage '''
    all_classes = Class.query.all()
    all_students = Student.query.all()
    all_professors = Professor.query.all()
    print(all_classes)
    return render_template('home.html',
        all_students=all_students, all_professors=all_professors, all_classes=all_classes)

@main.route('/create_student', methods=['GET', 'POST'])
@login_required
def create_student():
    ''' Route to create a Student '''
    form = StudentForm()

    # if form was submitted and contained no errors
    if form.validate_on_submit(): 
        new_student = Student(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            classes=form.classes.data
        )
        db.session.add(new_student)
        db.session.commit()

        flash('New student was created successfully.')
        return redirect(url_for('main.student_detail', student_id=new_student.id))
    return render_template('create_student.html', form=form)

@main.route('/student/<student_id>', methods=['GET', 'POST'])
@login_required
def student_detail(student_id):
    ''' Route to show Student details '''
    student = Student.query.get(student_id)
    form = StudentForm(obj=student)
    print(student.classes)

    # if form was submitted and contained no errors
    if form.validate_on_submit(): 
        student.first_name = form.first_name.data
        student.last_name = form.last_name.data
        student.classes = form.classes.data

        db.session.commit()

        flash('New student was updated successfully.')
        return redirect(url_for('main.student_detail', student_id=student_id))

    return render_template('student_detail.html', student=student, form=form)

@main.route('/create_professor', methods=['GET', 'POST'])
@login_required
def create_professor():
    ''' Route to create a Professor '''
    form = ProfessorForm()

    # if form was submitted and contained no errors
    if form.validate_on_submit(): 
        new_professor = Professor(
            first_name=form.first_name.data,
            last_name=form.last_name.data
        )
        db.session.add(new_professor)
        db.session.commit()

        flash('New professor was created successfully.')
        return redirect(url_for('main.professor_detail', professor_id=new_professor.id))
    return render_template('create_professor.html', form=form)

@main.route('/professor/<professor_id>', methods=['GET', 'POST'])
@login_required
def professor_detail(professor_id):
    ''' Route to show Professor details '''
    professor = Professor.query.get(professor_id)
    form = ProfessorForm(obj=professor)
    print(professor.classes)

    # if form was submitted and contained no errors
    if form.validate_on_submit(): 
        professor.first_name = form.first_name.data
        professor.last_name = form.last_name.data

        db.session.commit()

        flash('New professor was updated successfully.')
        return redirect(url_for('main.professor_detail', professor_id=professor_id))

    return render_template('professor_detail.html', professor=professor, form=form)

@main.route('/create_class', methods=['GET', 'POST'])
@login_required
def create_class():
    ''' Route to create a Class '''
    form = ClassForm()

    # if form was submitted and contained no errors
    if form.validate_on_submit(): 
        new_class = Class(
            title=form.title.data,
            professor=form.professor.data
        )
        db.session.add(new_class)
        db.session.commit()

        flash('New class was created successfully.')
        return redirect(url_for('main.class_detail', class_id=new_class.id))
    return render_template('create_class.html', form=form)

@main.route('/class/<class_id>', methods=['GET', 'POST'])
@login_required
def class_detail(class_id):
    ''' Route to show Class details '''
    class_object = Class.query.get(class_id)
    form = ClassForm(obj=class_object)

    # if form was submitted and contained no errors
    if form.validate_on_submit(): 
        class_object.title = form.title.data
        class_object.professor = form.professor.data

        db.session.commit()

        flash('New class was updated successfully.')
        return redirect(url_for('main.class_detail', class_id=class_id))

    return render_template('class_detail.html', class_object=class_object, form=form)

BEW-1.2-Final-Project/students_app/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>Students API</title>
    <link rel="stylesheet" href="/static/style.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <div id="content">
      <nav>
        <a href="/">Home</a>
        <div>
          {% if current_user.is_authenticated %}
          <a href="/create_student">Create Student</a>
          <a href="/create_professor">Create Professor</a>
          <a href="/create_class">Create Class</a>
          <a href="/logout">Log Out</a>
          {% else %}
          <a href="/signup">Sign Up</a>
          <a href="/login">Log In</a>
          {% endif %}
        </div>
      </nav>

      {% if current_user.is_authenticated %}
      <p>You are logged in as {{ current_user.username }}</p>
      {% endif %} 
      
      {% for message in get_flashed_messages() %}
      <p>{{ message }}</p>
      {% endfor %} 
      
      {% block content %}{% endblock %}

    </div>
  </body>
</html>

BEW-1.2-Final-Project/students_app/templates/class_detail.html
{% extends 'base.html' %} {% block content %}

<h1>{{ class_object.title }} by <a href="/professor/{{ class_object.professor.id }}">{{ class_object.professor.first_name }} {{ class_object.professor.last_name}}</a></h1>

<h3>Students</h3>
<ul>
  {% for student in class_object.students %}
  <li><a href="/student/{{ student.id }}">{{ student.first_name }} {{ student.last_name }}</a></li>
  {% endfor %}
</ul>

<form method="POST" action="{{ url_for('main.class_detail', class_id=class_object.id) }}">
  {{ form.csrf_token }}
  <fieldset>
    <legend>Edit {{ form.title.data }} Info</legend>

    {{ form.title.label }}
    {{ form.title }}

    {{ form.professor.label }}
    {{ form.professor }}

    {{ form.submit }}
  </fieldset>
</form>

{% endblock %}

BEW-1.2-Final-Project/students_app/templates/create_class.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" action="{{ url_for('main.create_class') }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter Class Details</legend>

        {{ form.title.label }}
        {{ form.title }}
        <ul>
        {% for error in form.title.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.professor.label }}
        {{ form.professor }}
        <ul>
        {% for error in form.professor.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        
        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

BEW-1.2-Final-Project/students_app/templates/create_professor.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" action="{{ url_for('main.create_professor') }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter a Professor's Credentials</legend>

        {{ form.first_name.label }}
        {{ form.first_name }}
        <ul>
        {% for error in form.first_name.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        
        {{ form.last_name.label }}
        {{ form.last_name }}
        <ul>
        {% for error in form.last_name.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        
        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

BEW-1.2-Final-Project/students_app/templates/create_student.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" action="{{ url_for('main.create_student') }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter a Student''s Credentials</legend>

        {{ form.first_name.label }}
        {{ form.first_name }}
        <ul>
        {% for error in form.first_name.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        
        {{ form.last_name.label }}
        {{ form.last_name }}
        <ul>
        {% for error in form.last_name.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.classes.label }}
        {{ form.classes }}
        <ul>
        {% for error in form.classes.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        
        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

BEW-1.2-Final-Project/students_app/templates/home.html
{% extends 'base.html' %}

{% block content %}



<div id="students-professors-list">
  <div>
    <h2>Students</h2>
    <p><a href="/create_student">+ New Student</a></p>
    <ul>
      {% for student in all_students %}
          <li><a href="/student/{{ student.id }}">{{ student.first_name }} {{ student.last_name}}</a></li>
      {% endfor %}
    </ul>
  </div>
  <div>
    <h2>Classes</h2>
    <p><a href="/create_class">+ New Class</a></p>
    <ul>
      {% for class in all_classes %}
          <li><a href="/class/{{ class.id }}">{{ class.title }}</a></li>
      {% endfor %}
    </ul>
  </div>
  <div>
    <h2>Professors</h2>
    <p><a href="/create_professor">+ New Professor</a></p>
    <ul>
      {% for professor in all_professors %}
          <li><a href="/professor/{{ professor.id }}">{{ professor.first_name }} {{ professor.last_name}}</a></li>
      {% endfor %}
    </ul>
  </div>
</div>




{% endblock %}

BEW-1.2-Final-Project/students_app/templates/login.html
{% extends 'base.html' %}
{% block content %}

<h1>Log In</h1>

<form action="/login" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

BEW-1.2-Final-Project/students_app/templates/professor_detail.html
{% extends 'base.html' %} {% block content %}

<h1>{{ professor.first_name }} {{ professor.last_name }}</h1>

<h3>Classes</h3>
<ul>
  {% for class in professor.classes %}
  <li><a href="/class/{{ class.id }}">{{ class.title }}</a></li>
  {% endfor %}
</ul>



<form method="POST" action="{{ url_for('main.professor_detail', professor_id=professor.id) }}">
  {{ form.csrf_token }}
  <fieldset>
    <legend>Edit {{ form.first_name.data }}'s Info</legend>

    {{ form.first_name.label }}
    {{ form.first_name }}

    {{ form.last_name.label }} 
    {{ form.last_name }}

    {{ form.submit }}
  </fieldset>
</form>

{% endblock %}

BEW-1.2-Final-Project/students_app/templates/signup.html
{% extends 'base.html' %}
{% block content %}

<h1>Sign Up</h1>

<form action="/signup" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}

    </fieldset>
</form>

{% endblock %}

BEW-1.2-Final-Project/students_app/templates/student_detail.html
{% extends 'base.html' %} {% block content %}

<h1>{{ student.first_name }} {{ student.last_name }}</h1>

<h3>Classes</h3>
<ul>
  {% for class in student.classes %}
  <li><a href="/class/{{ class.id }}">{{ class.title }}</a></li>
  {% endfor %}
</ul>


<form method="POST" action="{{ url_for('main.student_detail', student_id=student.id) }}">
  {{ form.csrf_token }}
  <fieldset>
    <legend>Edit {{ form.first_name.data }}'s Info</legend>

    {{ form.first_name.label }}
    {{ form.first_name }}

    {{ form.last_name.label }} 
    {{ form.last_name }}

    {{ form.classes.label}}
    {{ form.classes }}

    {{ form.submit }}
  </fieldset>
</form>

{% endblock %}