forms-lab/books_app/models.py
"""Create database models to represent tables."""
from books_app import db
from sqlalchemy.orm import backref
import enum

class FormEnum(enum.Enum):
    """Helper class to make it easier to use enums with forms."""
    @classmethod
    def choices(cls):
        return [(choice.name, choice) for choice in cls]

    def __str__(self):
        return str(self.value)

class Audience(FormEnum):
    CHILDREN = 'Children'
    YOUNG_ADULT = 'Young Adult'
    ADULT = 'Adult'
    ALL = 'All'

class Book(db.Model):
    """Book model."""
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(80), nullable=False)
    publish_date = db.Column(db.Date)

    # The author - Who wrote it?
    author_id = db.Column(db.Integer, db.ForeignKey('author.id'), nullable=False)
    author = db.relationship('Author', back_populates='books')
    
    # The audience - Who is this book written for?
    audience = db.Column(db.Enum(Audience), default=Audience.ALL)

    # The genres, e.g. fiction, sci-fi, fantasy
    genres = db.relationship(
        'Genre', secondary='book_genre', back_populates='books')

    # Who favorited this book?
    users_who_favorited = db.relationship(
        'User', secondary='user_book', back_populates='favorite_books')

    def __str__(self):
        return f'<Book: {self.title}>'

    def __repr__(self):
        return f'<Book: {self.title}>'

class Author(db.Model):
    """Author model."""
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    biography = db.Column(db.String(200))
    books = db.relationship('Book', back_populates='author')

    # def __str__(self):
    #     return f'<Author: {self.name}>'

    # def __repr__(self):
    #     return f'<Author: {self.name}>'

class Genre(db.Model):
    """Genre model."""
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False, unique=True)
    books = db.relationship(
        'Book', secondary='book_genre', back_populates='genres')

    def __str__(self):
        return f'<Genre: {self.name}>'

    def __repr__(self):
        return f'<Genre: {self.name}>'

book_genre_table = db.Table('book_genre',
    db.Column('book_id', db.Integer, db.ForeignKey('book.id')),
    db.Column('genre_id', db.Integer, db.ForeignKey('genre.id'))
)

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), nullable=False, unique=True)
    favorite_books = db.relationship(
        'Book', secondary='user_book', back_populates='users_who_favorited')

favorite_books_table = db.Table('user_book',
    db.Column('book_id', db.Integer, db.ForeignKey('book.id')),
    db.Column('user_id', db.Integer, db.ForeignKey('user.id'))
)

forms-lab/books_app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, DateField, SelectField, SubmitField, TextAreaField
from wtforms.ext.sqlalchemy.fields import QuerySelectField, QuerySelectMultipleField
from wtforms.validators import DataRequired, Length
from books_app.models import Audience, Book, Author, Genre

class BookForm(FlaskForm):
    """Form to create a book."""
    title = StringField('Book Title', validators=[DataRequired(), Length(min=3, max=80)])
    publish_date = DateField('Date Published')
    author = QuerySelectField('Author', query_factory=lambda: Author.query, allow_blank=False)
    audience = SelectField('Audience', choices=Audience.choices())
    genres = QuerySelectMultipleField('Genres', query_factory=lambda: Genre.query)
    submit = SubmitField('Submit')


class AuthorForm(FlaskForm):
    """Form to create an author."""
    # - the author's name
    author_name = StringField("Author Name", validators=[DataRequired(), Length(min=3, max=80)])
    # - the author's biography (hint: use a TextAreaField)
    biography = TextAreaField("Biography")
    # - a submit button
    submit = SubmitField('Submit')

    # STRETCH CHALLENGE: Add more fields here as well as in `models.py` to
    # collect more information about the author, such as their birth date,
    # country, etc.
    pass


class GenreForm(FlaskForm):
    """Form to create a genre."""

    name = StringField('Genre', validators=[DataRequired(), Length(min=3, max=80)])
    submit = SubmitField('Submit')

    # TODO: Fill out the fields in this class for:
    # - the genre's name (e.g. fiction, non-fiction, etc)
    # - a submit button
    pass

forms-lab/books_app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from books_app.config import Config
import os

app = Flask(__name__)
app.config.from_object(Config)
app.secret_key = os.urandom(24)

db = SQLAlchemy(app)

from books_app.routes import main

app.register_blueprint(main)

with app.app_context():
    db.create_all()

forms-lab/books_app/routes.py
"""Import packages and modules."""
import os
from flask import Blueprint, request, render_template, redirect, url_for, flash
from datetime import date, datetime
from books_app.models import Book, Author, Genre, User
from books_app.forms import BookForm, AuthorForm, GenreForm

# Import app and db from events_app package so that we can run app
from books_app import app, db

main = Blueprint("main", __name__)

##########################################
#           Routes                       #
##########################################

@main.route('/')
def homepage():
    all_books = Book.query.all()
    all_users = User.query.all()
    return render_template('home.html', 
        all_books=all_books, all_users=all_users)

@main.route('/create_book', methods=['GET', 'POST'])
def create_book():
    form = BookForm()

    # if form was submitted and contained no errors
    if form.validate_on_submit(): 
        new_book = Book(
            title=form.title.data,
            publish_date=form.publish_date.data,
            author=form.author.data,
            audience=form.audience.data,
            genres=form.genres.data
        )
        db.session.add(new_book)
        db.session.commit()

        flash('New book was created successfully.')
        return redirect(url_for('main.book_detail', book_id=new_book.id))
    return render_template('create_book.html', form=form)

@main.route('/create_author', methods=['GET', 'POST'])
def create_author():
    form = AuthorForm()

    if form.validate_on_submit():
      new_author = Author(
        author_name = form.author_name.data(),
        biography = form.biography.data()
      )
      db.session.add(new_author)
      db.session.commit()

      flash('New author was created successfully.')
      return redirect(url_for('main.homepage', author_id=new_author.id))

    return render_template('create_author.html', form=form)

@main.route('/create_genre', methods=['GET', 'POST'])
def create_genre():
    # TODO: Make a GenreForm instance
    form = GenreForm()

    if form.validate_on_submit():
      new_genre = Genre(
        genre = form.genre.data(),
      )
      db.session.add(new_genre)
      db.session.commit()

      flash('New genre was created successfully.')
      return redirect(url_for('main.homepage', genre_id=new_genre.id))

    # TODO: Send the form object to the template, and use it to render the form
    # fields
    return render_template('create_genre.html', form=form)

@main.route('/create_user', methods=['GET', 'POST'])
def create_user():
    # STRETCH CHALLENGE: Fill out the Create User route
    return "Not Yet Implemented"

@main.route('/book/<book_id>', methods=['GET', 'POST'])
def book_detail(book_id):
    book = Book.query.get(book_id)
    form = BookForm(obj=book)

    if form.validate_on_submit():
      book.query.filter_by(id=book_id)
      book.title = form.title.data()
      book.publish_date = form.publish_date.data()
      book.author_name = form.author.data()
      book.genre = form.genres.data()
      book.audience = form.audience.data()

    # TODO: If the form was submitted and is valid, update the fields in the 
    # Book object and save to the database, then flash a success message to the 
    # user and redirect to the book detail page

    return render_template('book_detail.html', book=book, form=form)

@main.route('/profile/<username>')
def profile(username):
    # TODO: Make a query for the user with the given username, and send to the
    # template

    # STRETCH CHALLENGE: Add ability to modify a user's username or favorite 
    # books
    return render_template('profile.html', username=username)

forms-lab/books_app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Books Site</title>
        <link rel="stylesheet" href="/static/style.css">
    </head>
    <body>
        <div id="content">
            {% for message in get_flashed_messages() %}
                <p>{{ message }}</p>
            {% endfor %}
            <a href="/">Home</a>
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

forms-lab/books_app/templates/book_detail.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ book.title }}</h1>

<p>
    <strong>Author</strong>: {{ book.author.name }}
</p>

<p>
    <strong>Author Bio</strong>: {{ book.author.biography }}
</p>

<p>
    <strong>Publish date</strong>: {{ book.publish_date }}
</p>

<p>
    <strong>Audience</strong>: {{ book.audience }}
</p>

<p>
    <strong>Genres</strong>: 
    
    {% for genre in book.genres %}
    {{ genre.name }},
    {% endfor %}
</p>

<form method="POST" action="{{ url_for('main.book_detail', book_id=book.id) }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Edit this book</legend>

        {{ form.title.label }}
        {{ form.title }}
        
        {{ form.publish_date.label }}
        {{ form.publish_date(placeholder="YYYY-mm-dd") }}
        
        {{ form.author.label }}
        {{ form.author }}
        
        {{ form.audience.label }}
        {{ form.audience }}
        
        {{ form.genres.label }}
        {{ form.genres }}
            
        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

forms-lab/books_app/templates/create_author.html
{% extends 'base.html' %}

{% block content %}

<p>Author creation form.</p>
<form method="POST" action="{{ url_for('main.create_author') }}">
  {{ form.csrf_token }}
  <fieldset>
    <legend>Enter a book</legend>

    {{ form.author_name.label }}
    {{ form.author_name }}

    {% for error in form.author_name.errors %}
      <p>{{ error }}</p>
    {% endfor %}

    {{ form.biography.label }}
    {{ form.biography }}
        
    {{ form.submit }}
  </fieldset>
</form>

<!-- TODO: Add a <form> element here and use the form variable to show the labels & fields -->

{% endblock %}

forms-lab/books_app/templates/create_book.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" action="{{ url_for('main.create_book') }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter a book</legend>

        {{ form.title.label }}
        {{ form.title }}

        {% for error in form.title.errors %}
          <p>{{ error }}</p>
        {% endfor %}
        
        {{ form.publish_date.label }}
        {{ form.publish_date(placeholder="YYYY-mm-dd") }}
        
        {{ form.author.label }}
        {{ form.author }}
        
        {{ form.audience.label }}
        {{ form.audience }}
        
        {{ form.genres.label }}
        {{ form.genres }}
            
        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}
w

forms-lab/books_app/templates/create_genre.html
{% extends 'base.html' %}

{% block content %}

<p>Genre creation form.</p>

<!-- TODO: Add a <form> element here and use the form variable to show the labels & fields -->
  <form method="POST" action="{{ url_for('main.create_genre') }}">
    {{ form.csrf_token }}
    <fieldset>
      <legend>Enter a genre</legend>
  
      {{ form.name.label }}
      {{ form.name }}

      {% for error in form.name.errors %}
        <p>{{ error }}</p>
      {% endfor %}
          
      {{ form.submit }}
    </fieldset>
  </form>

{% endblock %}

forms-lab/books_app/templates/home.html
{% extends 'base.html' %}

{% block content %}

<h2>Books</h2>

<p>
    <a href="/create_book">+ New Book</a>
</p>

<p>
    <a href="/create_author">+ New Author</a>
</p>

<p>
    <a href="/create_genre">+ New Genre</a>
</p>

<ul>
{% for book in all_books %}
    <li><a href="/book/{{ book.id }}">{{ book.title }}</a> by {{ book.author.name }}</li>
{% endfor %}
</ul>

<h2>Users</h2>

<p>
    <a href="/create_user">+ New User</a>
</p>

<ul>
    {% for user in all_users %}
        <li><a href="/profile/{{ user.username }}">{{ user.username }}</a></li>
    {% endfor %}
</ul>



{% endblock %}